### ISSUE TITLE
some typos

### ISSUE THREAD

**Issue by beginner3456789** [jakkan/install-scripts#1]
This works. 
[fde-github-jakkan.sh.txt](https://github.com/jakkan/install-scripts/files/10889013/fde-github-jakkan.sh.txt)
I am not good with github and couldn't easily get a pull request so maybe you can just browse the file and close out any time.

Edit: The kernel params might not be perfect except the passphrase is only needed once so that is nice:
[    0.054417] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-6.1.14_1 root=UUID=439913e8-2a64-45f4-982a-b
0c9b17ceb2b ro rd.luks.uuid=e5860a9b-69f9-45a5-87d3-7fbf766da69d cryptkey=/boot/volume.key loglevel=4
[    0.054488] Unknown kernel command line parameters "BOOT_IMAGE=/boot/vmlinuz-6.1.14_1 cryptkey=/boot/v
olume.key", will be passed to user space.

**Comment by jakkan** [comment]
Thanks for help! Your script gave me some ideas. I think I the latest commit is also largely working, but with a volume group.
